Adding completions and install --list option

diff --git a/libexec/helmenv-install b/libexec/helmenv-install
--- a/libexec/helmenv-install
+++ b/libexec/helmenv-install
@@ -18,16 +18,33 @@ else
   version="${1}"
 fi
 
-dst_path="${HELMENV_ROOT}/versions/${version}/bin"
+## helmenv install --list
+HELM_REPO='https://api.github.com/repos/helm/helm/releases'
+test "$1" == "--list" -o "$1" == "-l" && {
+  eval which {wget,curl,jq} &>/dev/null || { echo Please install wget curl jq ; exit 0; }
+  next="${HELM_REPO}?simple=yes&per_page=100&page="
+  page="1"
+  while true; do
+    versions=$(wget -qO- "${next}${page}" | jq -r '.[].tag_name')
+    echo $versions
+    export next=$(curl -sSLIvk "${next}${page}" 2>&1 | grep -m1 link | sed 's|.*page=\(.*\)>;|\1|g'|xargs -n1 )
+    echo $next
+    page=$(cut -d' ' -f1 <<<$next)
+    grep -q last <<<${next} && break
+  done
+  exit 0
+}
+
+dst_path="${HELMENV_ROOT}/versions/${version##v}/bin"
 if [ -f "${dst_path}/helm" ]; then
-  echo "helm v${version} is already installed"
+  echo "helm ${version##v} is already installed"
   exit 0
 fi
 
-info "Installing helm v${version}"
+info "Installing helm ${version##v}"
 mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"
 
 curl -f https://raw.githubusercontent.com/helm/helm/master/scripts/get | \
-  HELM_INSTALL_DIR="$dst_path" bash -s - --version "v${version}" --no-sudo >&2 || error_and_die "Install failed"
+  HELM_INSTALL_DIR="$dst_path" bash -s - --version "v${version##v}" --no-sudo >&2 || error_and_die "Install failed"
 
-info "Installation of helm v${version} successful"
+info "Installation of helm ${version##v} successful"
